// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rudderlabs/rudder-server/router/batchrouter/asyncdestinationmanager/sendgrid-bulk-upload (interfaces: SendGridAPIService)
//
// Generated by this command:
//
//	mockgen -destination=../../../../mocks/router/sendgridbulkupload/sendgridbulkupload_mock.go -package=mocks github.com/rudderlabs/rudder-server/router/batchrouter/asyncdestinationmanager/sendgrid-bulk-upload SendGridAPIService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	sendgridbulkupload "github.com/rudderlabs/rudder-server/router/batchrouter/asyncdestinationmanager/sendgrid-bulk-upload"
	gomock "go.uber.org/mock/gomock"
)

// MockSendGridAPIService is a mock of SendGridAPIService interface.
type MockSendGridAPIService struct {
	ctrl     *gomock.Controller
	recorder *MockSendGridAPIServiceMockRecorder
	isgomock struct{}
}

// MockSendGridAPIServiceMockRecorder is the mock recorder for MockSendGridAPIService.
type MockSendGridAPIServiceMockRecorder struct {
	mock *MockSendGridAPIService
}

// NewMockSendGridAPIService creates a new mock instance.
func NewMockSendGridAPIService(ctrl *gomock.Controller) *MockSendGridAPIService {
	mock := &MockSendGridAPIService{ctrl: ctrl}
	mock.recorder = &MockSendGridAPIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSendGridAPIService) EXPECT() *MockSendGridAPIServiceMockRecorder {
	return m.recorder
}

// GetImportErrors mocks base method.
func (m *MockSendGridAPIService) GetImportErrors(errorsURL string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImportErrors", errorsURL)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImportErrors indicates an expected call of GetImportErrors.
func (mr *MockSendGridAPIServiceMockRecorder) GetImportErrors(errorsURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImportErrors", reflect.TypeOf((*MockSendGridAPIService)(nil).GetImportErrors), errorsURL)
}

// GetImportStatus mocks base method.
func (m *MockSendGridAPIService) GetImportStatus(jobID string) (*sendgridbulkupload.ImportStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImportStatus", jobID)
	ret0, _ := ret[0].(*sendgridbulkupload.ImportStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImportStatus indicates an expected call of GetImportStatus.
func (mr *MockSendGridAPIServiceMockRecorder) GetImportStatus(jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImportStatus", reflect.TypeOf((*MockSendGridAPIService)(nil).GetImportStatus), jobID)
}

// UploadContacts mocks base method.
func (m *MockSendGridAPIService) UploadContacts(request sendgridbulkupload.UpsertRequest) (*sendgridbulkupload.UpsertResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadContacts", request)
	ret0, _ := ret[0].(*sendgridbulkupload.UpsertResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadContacts indicates an expected call of UploadContacts.
func (mr *MockSendGridAPIServiceMockRecorder) UploadContacts(request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadContacts", reflect.TypeOf((*MockSendGridAPIService)(nil).UploadContacts), request)
}
